"""initial_schema

Revision ID: e514d1f84b45
Revises: 
Create Date: 2026-03-30 10:33:00.255834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e514d1f84b45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('asset_type', sa.Enum('STOCK', 'ETF', 'FUND', 'SUKUK', 'BOND', 'CASH', 'REIT', 'OTHER', name='assettype'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'from_currency', 'to_currency', name='uq_fx_date_pair')
    )
    op.create_index(op.f('ix_fx_rates_date'), 'fx_rates', ['date'], unique=False)
    op.create_index(op.f('ix_fx_rates_id'), 'fx_rates', ['id'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('BROKERAGE', 'ROBO', 'SUKUK', 'DEAL', 'CROWDFUNDING', 'OTHER', name='platformcategory'), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_id'), 'platforms', ['id'], unique=False)
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('account_type', sa.Enum('INDIVIDUAL', 'JOINT', 'RETIREMENT', 'MARGIN', 'OTHER', name='accounttype'), nullable=False),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_platform_id'), 'accounts', ['platform_id'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('import_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('mapping_name', sa.String(length=100), nullable=False),
    sa.Column('mapping_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_mappings_id'), 'import_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_import_mappings_platform_id'), 'import_mappings', ['platform_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_price_asset_date')
    )
    op.create_index(op.f('ix_price_history_asset_id'), 'price_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_price_history_date'), 'price_history', ['date'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('deal_type', sa.Enum('REAL_ESTATE', 'EQUITY', 'DEBT', 'SUKUK', 'MURABAHA', 'FUND', 'COMMODITY', 'OTHER', name='dealtype'), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('target_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXITED', 'DEFAULTED', 'MATURED', 'PENDING', name='dealstatus'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_account_id'), 'deals', ['account_id'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_platform_id'), 'deals', ['platform_id'], unique=False)
    op.create_index(op.f('ix_deals_user_id'), 'deals', ['user_id'], unique=False)
    op.create_table('raw_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('import_status', sa.Enum('PENDING', 'PREVIEW', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='importstatus'), nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_imported', sa.Integer(), nullable=True),
    sa.Column('rows_skipped', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_imports_id'), 'raw_imports', ['id'], unique=False)
    op.create_index(op.f('ix_raw_imports_platform_id'), 'raw_imports', ['platform_id'], unique=False)
    op.create_index(op.f('ix_raw_imports_user_id'), 'raw_imports', ['user_id'], unique=False)
    op.create_table('deal_cashflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('cashflow_type', sa.Enum('INVESTMENT', 'DISTRIBUTION', 'REDEMPTION', 'FEE', 'VALUATION', 'PROJECTED', name='cashflowtype'), nullable=False),
    sa.Column('cashflow_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('raw_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['raw_import_id'], ['raw_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_cashflows_cashflow_date'), 'deal_cashflows', ['cashflow_date'], unique=False)
    op.create_index(op.f('ix_deal_cashflows_deal_id'), 'deal_cashflows', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_cashflows_id'), 'deal_cashflows', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'FEE', 'DEPOSIT', 'WITHDRAWAL', 'FX', 'SPLIT', 'BONUS', 'RIGHTS', name='transactiontype'), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fees', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('raw_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['raw_import_id'], ['raw_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_asset_id'), 'transactions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_trade_date'), 'transactions', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_trade_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_asset_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_deal_cashflows_id'), table_name='deal_cashflows')
    op.drop_index(op.f('ix_deal_cashflows_deal_id'), table_name='deal_cashflows')
    op.drop_index(op.f('ix_deal_cashflows_cashflow_date'), table_name='deal_cashflows')
    op.drop_table('deal_cashflows')
    op.drop_index(op.f('ix_raw_imports_user_id'), table_name='raw_imports')
    op.drop_index(op.f('ix_raw_imports_platform_id'), table_name='raw_imports')
    op.drop_index(op.f('ix_raw_imports_id'), table_name='raw_imports')
    op.drop_table('raw_imports')
    op.drop_index(op.f('ix_deals_user_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_platform_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_account_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_date'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_asset_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_import_mappings_platform_id'), table_name='import_mappings')
    op.drop_index(op.f('ix_import_mappings_id'), table_name='import_mappings')
    op.drop_table('import_mappings')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_platform_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_id'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_fx_rates_id'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_date'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
